server:
  port: 9092 # 服务端口

spring:
  application:
    name: user-rest  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.128:8848
      config:
        server-addr: 192.168.111.128:8848

user:
  name: max
  age: 24