server:
  port: 9090 # 服务端口

spring:
  application:
    name: userrest  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.128:8848
      config:
        server-addr: 192.168.111.128:8848
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.200.97:3306/sys_info?useUnicode=true&characterEncoding=utf8
      username: ejltest
      password: testonly2016
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.200.97:3306/sys_info?useUnicode=true&characterEncoding=utf8
      username: ejltest
      password: testonly2016
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
# 是否连接数据库
ejlerp:
  dts:
    useDb: true

api:
  rest:
    dtsOrderServer: 1111
    dts-item-server: 222
