server:
  port: 9090 # 服务端口

spring:
  application:
    name: userrest  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.128:8848
      config:
        server-addr: 192.168.111.128:8848

